unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

set-option -g status-position top
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

set -g default-terminal "screen-256color"
set -as terminal-features ",tmux-256color:RGB"
set -sg escape-time 10
set -g display-time 2000
set -g repeat-time 300
set -g status-interval 5
setw -g aggressive-resize on

# Activate OFF mode
bind -n M-o \
    set prefix None \;\
    set key-table off \;\
    rename-session "#{session_name}-OFF"

# Disable OFF mode
bind -T off M-O \
    set -u prefix \;\
    set -u key-table \;\
    rename-session '#{s|-OFF||:session_name}'

# bring pane from another window into current window
bind L choose-window 'join-pane -h -s "%%"'  # add as horizontal split (add to the right)
bind J choose-window 'join-pane -s "%%"'  # add as vertical split (add below)
# more intuitive window split
# prefix E spreads panes out evenly without affecting layout
bind \\ split-window -h
bind - split-window -v
bind M-\\ split-window -bh  # -b option splits above/left of
bind M-- split-window -bv
#split below/right of _all_ panes
bind S-\\ split-window -fh
bind S-- split-window -fv
bind C-\\ split-window -bfh
bind C-- split-window -bfv
# -r sets command with repeat-time
# cycle through windows in number order
bind -r C-p previous-window
bind -r C-n next-window
# <prefix> l is taken by pane navigation
bind p last-window
# vim like pane navigation
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# popup binds
bind C-h display-popup -h 80% -w 80% "tmux list-keys | less"
bind C-f run-shell '\
    if [ "#{session_name}" = popup ]; then\
        tmux detach-client; \
    else \
        tmux display-popup -h 80% -w 80% -E "tmux attach -t popup || tmux new -s popup"; \
    fi \
'

set -ogqF @config_dir "#{d:current_file}"
bind-key R source-file -F "#{@config_dir}/tmux.conf" \; display-message "Config Reloaded"

set -g @plugin 'tmux-plugins/tpm'  # <prefix> I to install, <prefix> U to update, <prefix> alt+u to uninstall
set -g @plugin 'tmux-plugins/tmux-resurrect'  # <prefix> C-s to save, <prefix> C-r to load
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'sainnhe/tmux-fzf'

set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'
if-shell '[ $(tmux display -p "#{window_width}") -gt 110 ]' \
    "TMUX_FZF_OPTIONS='-p -w 100 -h 20 -m'" \
    "TMUX_FZF_OPTIONS='-p -w 90% -h 90% -m'"

source-file -F "#{@config_dir}/tmux.theme.conf" 

if "test ! -d #{@config_dir}/plugins/tpm" \
  "run 'git clone https:/github.com/tmux-plugins/tpm #{@config_dir}/plugins/tpm && #{@config_dir}/plugins/tpm/bin/install_plugins'"
run "#{@config_dir}/plugins/tpm/tpm"
