set -ogq @thm_rosewater "#dc8a78"
set -ogq @thm_pink "#ea76cb"
set -ogq @thm_red "#d20f39"
set -ogq @thm_peach "#fe640b"
set -ogq @thm_green "#40a02b"
set -ogq @thm_lavender "#7287fd"
set -ogq @thm_surface_1 "#bcc0cc"
set -ogq @thm_base "#eff1f5"

set -g mode-style 'bg=#{@thm_surface_1}'
set -g copy-mode-match-style 'bg=#{@thm_surface_1} fg=#{@thm_base}'
set -g copy-mode-current-match-style 'bg=#{@thm_peach} fg=#{@thm_base}'
set -g message-style 'fg=#{@thm_lavender} bg=#{@thm_base}'
set -gF prompt-cursor-colour '#{@thm_lavender}'
set -gF clock-mode-colour '#{@thm_peach}'

set -gF display-panes-colour '#{@thm_surface_1}'
set -gF display-panes-active-colour '#{@thm_peach}'
set -g pane-border-style 'fg=#{@thm_surface_1}'
set -g pane-active-border-style 'fg=#{@thm_peach}'
set -g window-style 'bg=#{@thm_base}'  # I think border color indicator is more pleasing, but this can also be changed
set -g window-active-style 'bg=#{@thm_base}'

set -g status-style 'bg=#{@thm_base}'
set -g status-left ''
set -g status-right-length 200

set -g status-right '#[bg=#{@thm_base},fg=#{@thm_rosewater}]#[fg=#{@thm_base},bg=#{@thm_rosewater}] ┃ #{b:pane_current_path}#[bg=#{@thm_base},fg=#{@thm_rosewater}] '
set -ag status-right '#[bg=#{@thm_base},fg=#{@thm_lavender}]#[fg=#{@thm_base},bg=#{@thm_lavender}] ┃ #{user}#[bg=#{@thm_base},fg=#{@thm_lavender}] '
set -ag status-right '#[bg=#{@thm_base},fg=#{@thm_pink}]#[fg=#{@thm_base},bg=#{@thm_pink}]󰒋 ┃ #{host}#[bg=#{@thm_base},fg=#{@thm_pink}] '
set -ag status-right '#{?client_prefix,#[fg=#{@thm_red}]#[bg=#{@thm_base}]#[bg=#{@thm_red}]#[fg=#{@thm_base}] ,#[fg=#{@thm_green}]#[bg=#{@thm_base}]#[bg=#{@thm_green}]#[fg=#{@thm_base}] }'
set -ag status-right '#{?client_prefix,#[bg=#{@thm_red}]#[fg=#{@thm_base}]┃ #{session_name}#[bg=#{@thm_base}]#[fg=#{@thm_red}],#[bg=#{@thm_green}]#[fg=#{@thm_base}]┃ #{session_name}#[bg=#{@thm_base}]#[fg=#{@thm_green}]}'

set -g window-status-current-format '#[bg=#{@thm_base},fg=#{@thm_peach}]#[fg=#{@thm_base},bg=#{@thm_peach}]#I ┃ #W'
set -ag window-status-current-format '#{?window_activity_flag, 󱅫,}#{?window_bell_flag, 󰂞,}#{?window_silence_flag, 󰂛,}#{?window_active,,}#{?window_last_flag, 󰖰,}#{?window_marked_flag, 󰃀,}#{?window_zoomed_flag, 󰁌,}'
set -ag window-status-current-format '#[bg=#{@thm_base},fg=#{@thm_peach}]'
set -g window-status-format '#[bg=#{@thm_base},fg=#{@thm_surface_1}]#[fg=#{@thm_base},bg=#{@thm_surface_1}]#I ┃ #W'
set -ag window-status-format '#{?window_activity_flag, 󱅫,}#{?window_bell_flag, 󰂞,}#{?window_silence_flag, 󰂛,}#{?window_active,,}#{?window_last_flag, 󰖰,}#{?window_marked_flag, 󰃀,}#{?window_zoomed_flag, 󰁌,}'
set -ag window-status-format '#[bg=#{@thm_base},fg=#{@thm_surface_1}]'

set -g popup-border-lines 'rounded'
set -g popup-border-style 'fg=#{@thm_lavender}'
